import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  vwContent: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
  },
  headerPrincipal: {
    height: 60,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    borderBottomWidth: 1.5,
    borderColor: 'rgba(49, 148, 158,0.1)',
  },
  txtHeaderPrincipal: {
    fontSize: 25,
    fontWeight: 'bold',
    width: '100%',
    textAlign: 'center',
    color: '#31949e',
  },
  tchHeaderMenu: {
    width: 60,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
  },
  txtShadow: {
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: {width: -0.5, height: 0.5},
    textShadowRadius: 1,
  },
  vwBoxInputs: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vwBoxInput: {
    flexDirection: 'row',
  },
  txtTopIcon: {
    color: '#31949e',
    fontWeight: 'bold',
  },
  inpWeight: {
    height: 40,
    padding: 0,
    width: 80,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 3,
    borderColor: '#31949e',
    textAlign: 'center',
    color: '#31949e',
    fontSize: 18,
    fontWeight: 'bold',
  },
  vwBoxRightInside: {
    justifyContent: 'flex-end',
  },
  txtRightInside: {
    fontSize: 17,
    marginLeft: 2,
    color: '#31949e',
    fontWeight: 'bold',
  },
  vwBoxIcon: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconSup: {
    marginBottom: 3,
    marginTop: 3,
  },
  vwSuperiorBox: {
    padding: 10,
    backgroundColor: '#FFFFFF',
    width: '85%',
    borderRadius: 10,
    paddingBottom: 15,
  },
  vwBoxDivide: {
    alignSelf: 'flex-end',
    marginRight: 15,
    marginLeft: 15,
  },
  vwBtnCalc: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 10,
  },
  tchCalc: (disabled) => ({
    backgroundColor: disabled ? 'rgba(255,255,255,0.7)' : '#31949e',
    padding: 5,
    paddingRight: 20,
    paddingLeft: 20,
    borderRadius: 20,
    elevation: 3,
  }),
  txtTchCalc: (disabled) => ({
    fontSize: 18,
    color: disabled ? 'rgba(51,51,51,0.15)' : '#FFFFFF',
    fontWeight: 'bold',
  }),
  vwContentPie: {
    width: 200,
    height: 200,
    borderRadius: 100,
    elevation: 2,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pieGraph: {
    borderRadius: 100,
  },
  vwBackWhite: {
    height: 140,
    width: 140,
    backgroundColor: '#FFFFFF',
    position: 'absolute',
    borderRadius: 85,
    justifyContent: 'center',
    alignItems: 'center',
  },
  vwBackWhitePies: {
    height: 170,
    width: 170,
  },
  txtCenterPrincipal: {
    fontSize: 25,
    color: '#31949e',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  vwNumberHeight: {
    backgroundColor: '#FFFFFF',
    paddingRight: 3.7,
    paddingLeft: 3.7,
    paddingBottom: 1,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#31949e',
    position: 'absolute',
    right: -3,
    top: 0,
  },
  txtNumberHeight: {
    fontSize: 7,
    fontWeight: 'bold',
    color: '#31949e',
  },
  vwBoxPie: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 10,
  },
  btnRemoveIMC: {
    height: 25,
    width: 25,
    backgroundColor: '#FFFFFF',
    position: 'absolute',
    bottom: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  vwTableInfo: {
    height: 200,
    width: '100%',
    paddingRight: 10,
    paddingLeft: 10,
    borderTopWidth: 1.5,
    borderColor: 'rgba(49, 148, 158,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  boxRowTable: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
  },
  vwContentTable: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  vwColorTab: (cor, check, res) => ({
    height: 19.5,
    width: 19.5,
    marginBottom: 2,
    marginTop: 2,
    borderRadius: 15,
    backgroundColor: cor,
    borderWidth: res && cor != check ? 4 : 0,
    borderColor: 'transparent',
  }),
  txtTitleTable: {
    fontWeight: 'bold',
    color: '#31949e',
    fontSize: 17,
    marginBottom: 10,
  },
  txtTableInfos: {
    marginBottom: 2,
    marginTop: 2,
    fontWeight: 'bold',
    color: '#333',
  },
  svContent: {
    width: '100%',
  },
  vwPrimaryBox: {
    justifyContent: 'flex-start',
    width: '100%',
    alignItems: 'center',
    flex: 1,
  },
  vwResultTxt: {
    alignSelf: 'center',
    marginBottom: 5,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 7,
    paddingRight: 15,
    paddingLeft: 15,
    borderRadius: 25,
  },
  txtResultLabel: (cor) => ({
    fontSize: 25,
    fontWeight: 'bold',
    textAlign: 'center',
    color: cor,
  }),
});

export default styles;
